insert into students (id, age, department, firt_name, last_name) values (1, 45, 'Marketing', 'Maggy', 'Killik');
insert into students (id, age, department, firt_name, last_name) values (2, 24, 'Training', 'Elvin', 'Pottinger');
insert into students (id, age, department, firt_name, last_name) values (3, 23, 'Legal', 'Noel', 'Tomkys');
insert into students (id, age, department, firt_name, last_name) values (4, 20, 'Marketing', 'Tamar', 'Abbey');
insert into students (id, age, department, firt_name, last_name) values (5, 26, 'Training', 'Ailene', 'Hebbs');
insert into students (id, age, department, firt_name, last_name) values (6, 27, 'Research and Development', 'Ryon', 'Durbridge');
insert into students (id, age, department, firt_name, last_name) values (7, 39, 'Sales', 'Mil', 'Lynnitt');
insert into students (id, age, department, firt_name, last_name) values (8, 26, 'Product Management', 'Dolli', 'Stodart');
insert into students (id, age, department, firt_name, last_name) values (9, 23, 'Legal', 'Lauraine', 'Birtwistle');
insert into students (id, age, department, firt_name, last_name) values (10, 46, 'Support', 'Aurlie', 'Ibbotson');
insert into students (id, age, department, firt_name, last_name) values (11, 25, 'Training', 'Tait', 'Grishelyov');
insert into students (id, age, department, firt_name, last_name) values (12, 24, 'Support', 'Buck', 'Ickovicz');
insert into students (id, age, department, firt_name, last_name) values (13, 25, 'Services', 'Hillard', 'Le Sieur');
insert into students (id, age, department, firt_name, last_name) values (14, 26, 'Engineering', 'Donna', 'Dikles');
insert into students (id, age, department, firt_name, last_name) values (15, 19, 'Sales', 'Emmanuel', 'Stolting');
insert into students (id, age, department, firt_name, last_name) values (16, 38, 'Services', 'Virgina', 'Peach');
insert into students (id, age, department, firt_name, last_name) values (17, 33, 'Marketing', 'Lyndsie', 'Tanswell');
insert into students (id, age, department, firt_name, last_name) values (18, 48, 'Training', 'Mickey', 'Antunes');
insert into students (id, age, department, firt_name, last_name) values (19, 38, 'Accounting', 'Kiersten', 'Woodbridge');
insert into students (id, age, department, firt_name, last_name) values (20, 25, 'Legal', 'Dorian', 'Brinklow');
insert into students (id, age, department, firt_name, last_name) values (21, 49, 'Research and Development', 'Greer', 'Starzaker');
insert into students (id, age, department, firt_name, last_name) values (22, 19, 'Accounting', 'Marci', 'Janczewski');
insert into students (id, age, department, firt_name, last_name) values (23, 23, 'Services', 'Monty', 'Wands');
insert into students (id, age, department, firt_name, last_name) values (24, 27, 'Legal', 'Berky', 'Attride');
insert into students (id, age, department, firt_name, last_name) values (25, 49, 'Training', 'Christoper', 'Poore');
insert into students (id, age, department, firt_name, last_name) values (26, 32, 'Business Development', 'Deni', 'Chinge de Hals');
insert into students (id, age, department, firt_name, last_name) values (27, 47, 'Services', 'Ursuline', 'Godfree');
insert into students (id, age, department, firt_name, last_name) values (28, 37, 'Business Development', 'Perri', 'Costy');
insert into students (id, age, department, firt_name, last_name) values (29, 31, 'Services', 'Jorge', 'Danilishin');
insert into students (id, age, department, firt_name, last_name) values (30, 34, 'Legal', 'Tarrah', 'Denham');
insert into students (id, age, department, firt_name, last_name) values (31, 43, 'Research and Development', 'Romain', 'Carlick');
insert into students (id, age, department, firt_name, last_name) values (32, 34, 'Engineering', 'Win', 'Budgeon');
insert into students (id, age, department, firt_name, last_name) values (33, 40, 'Product Management', 'Alister', 'Fick');
insert into students (id, age, department, firt_name, last_name) values (34, 49, 'Engineering', 'Denna', 'Klimov');
insert into students (id, age, department, firt_name, last_name) values (35, 33, 'Accounting', 'Abbey', 'Scathard');
insert into students (id, age, department, firt_name, last_name) values (36, 46, 'Sales', 'Flss', 'Marlow');
insert into students (id, age, department, firt_name, last_name) values (37, 49, 'Business Development', 'Francklyn', 'Knell');
insert into students (id, age, department, firt_name, last_name) values (38, 27, 'Support', 'Curtice', 'Colley');
insert into students (id, age, department, firt_name, last_name) values (39, 43, 'Sales', 'Torey', 'Peete');
insert into students (id, age, department, firt_name, last_name) values (40, 48, 'Sales', 'Shelly', 'Rosettini');
insert into students (id, age, department, firt_name, last_name) values (41, 24, 'Accounting', 'Morse', 'Lammerding');
insert into students (id, age, department, firt_name, last_name) values (42, 26, 'Human Resources', 'Jenna', 'Brockley');
insert into students (id, age, department, firt_name, last_name) values (43, 25, 'Services', 'Reamonn', 'Kleint');
insert into students (id, age, department, firt_name, last_name) values (44, 44, 'Research and Development', 'Mozes', 'Rosensaft');
insert into students (id, age, department, firt_name, last_name) values (45, 41, 'Sales', 'Salomo', 'Richmont');
insert into students (id, age, department, firt_name, last_name) values (46, 37, 'Business Development', 'Sallie', 'Seckington');
insert into students (id, age, department, firt_name, last_name) values (47, 47, 'Research and Development', 'Lanita', 'Peizer');
insert into students (id, age, department, firt_name, last_name) values (48, 33, 'Services', 'Corbin', 'Stebbings');
insert into students (id, age, department, firt_name, last_name) values (49, 35, 'Training', 'Adrian', 'Chevalier');
insert into students (id, age, department, firt_name, last_name) values (50, 43, 'Research and Development', 'Kaylee', 'Riley');
insert into students (id, age, department, firt_name, last_name) values (51, 48, 'Business Development', 'Julie', 'Hamblen');
insert into students (id, age, department, firt_name, last_name) values (52, 48, 'Services', 'Rochette', 'Daffey');
insert into students (id, age, department, firt_name, last_name) values (53, 37, 'Accounting', 'Veradis', 'Cranshaw');
insert into students (id, age, department, firt_name, last_name) values (54, 33, 'Business Development', 'Grover', 'Le Count');
insert into students (id, age, department, firt_name, last_name) values (55, 27, 'Services', 'Kiersten', 'O''Lennane');
insert into students (id, age, department, firt_name, last_name) values (56, 42, 'Human Resources', 'Alyssa', 'Boddington');
insert into students (id, age, department, firt_name, last_name) values (57, 50, 'Sales', 'Templeton', 'Battams');
insert into students (id, age, department, firt_name, last_name) values (58, 28, 'Legal', 'Ally', 'Stroban');
insert into students (id, age, department, firt_name, last_name) values (59, 34, 'Sales', 'Naoma', 'Boow');
insert into students (id, age, department, firt_name, last_name) values (60, 47, 'Marketing', 'Waldon', 'Drakeley');
insert into students (id, age, department, firt_name, last_name) values (61, 40, 'Sales', 'Morly', 'Tunstall');
insert into students (id, age, department, firt_name, last_name) values (62, 32, 'Training', 'Anne-corinne', 'Grishanov');
insert into students (id, age, department, firt_name, last_name) values (63, 45, 'Marketing', 'Wilfred', 'McMeekin');
insert into students (id, age, department, firt_name, last_name) values (64, 27, 'Marketing', 'Marlon', 'Iannitti');
insert into students (id, age, department, firt_name, last_name) values (65, 35, 'Human Resources', 'Thacher', 'Molineux');
insert into students (id, age, department, firt_name, last_name) values (66, 29, 'Legal', 'Darci', 'Cowpertwait');
insert into students (id, age, department, firt_name, last_name) values (67, 25, 'Product Management', 'Cletis', 'Gleadhall');
insert into students (id, age, department, firt_name, last_name) values (68, 42, 'Accounting', 'Gregorius', 'Ivanov');
insert into students (id, age, department, firt_name, last_name) values (69, 23, 'Product Management', 'Aleen', 'McCrachen');
insert into students (id, age, department, firt_name, last_name) values (70, 47, 'Accounting', 'Hedvig', 'McCotter');
insert into students (id, age, department, firt_name, last_name) values (71, 38, 'Product Management', 'Davita', 'Bedminster');
insert into students (id, age, department, firt_name, last_name) values (72, 24, 'Training', 'Candide', 'Verdun');
insert into students (id, age, department, firt_name, last_name) values (73, 38, 'Engineering', 'Dyanne', 'Birds');
insert into students (id, age, department, firt_name, last_name) values (74, 49, 'Accounting', 'Steffane', 'Steeples');
insert into students (id, age, department, firt_name, last_name) values (75, 23, 'Research and Development', 'Kinny', 'Klimowicz');
insert into students (id, age, department, firt_name, last_name) values (76, 20, 'Human Resources', 'Ringo', 'Schwerin');
insert into students (id, age, department, firt_name, last_name) values (77, 36, 'Accounting', 'Denise', 'Bradie');
insert into students (id, age, department, firt_name, last_name) values (78, 26, 'Human Resources', 'Yoko', 'Rockey');
insert into students (id, age, department, firt_name, last_name) values (79, 44, 'Product Management', 'Garwood', 'Manwaring');
insert into students (id, age, department, firt_name, last_name) values (80, 44, 'Sales', 'Rolf', 'Iacoboni');
insert into students (id, age, department, firt_name, last_name) values (81, 45, 'Marketing', 'Phillipe', 'Wynes');
insert into students (id, age, department, firt_name, last_name) values (82, 49, 'Product Management', 'Paloma', 'Jeanin');
insert into students (id, age, department, firt_name, last_name) values (83, 47, 'Engineering', 'Inger', 'Bolwell');
insert into students (id, age, department, firt_name, last_name) values (84, 32, 'Product Management', 'Glynda', 'MacAllen');
insert into students (id, age, department, firt_name, last_name) values (85, 43, 'Marketing', 'Allianora', 'Flinn');
insert into students (id, age, department, firt_name, last_name) values (86, 33, 'Product Management', 'Dom', 'Almey');
insert into students (id, age, department, firt_name, last_name) values (87, 41, 'Sales', 'Maryann', 'Lakin');
insert into students (id, age, department, firt_name, last_name) values (88, 44, 'Training', 'Larissa', 'Bernardet');
insert into students (id, age, department, firt_name, last_name) values (89, 26, 'Support', 'Mahalia', 'Ledgister');
insert into students (id, age, department, firt_name, last_name) values (90, 49, 'Human Resources', 'Deeyn', 'Drynan');
insert into students (id, age, department, firt_name, last_name) values (91, 41, 'Human Resources', 'Katee', 'Dybald');
insert into students (id, age, department, firt_name, last_name) values (92, 39, 'Sales', 'Jasun', 'Jimmes');
insert into students (id, age, department, firt_name, last_name) values (93, 23, 'Product Management', 'Jeni', 'Ashwin');
insert into students (id, age, department, firt_name, last_name) values (94, 50, 'Marketing', 'Hadleigh', 'Huglin');
insert into students (id, age, department, firt_name, last_name) values (95, 27, 'Accounting', 'Tracie', 'Furney');
insert into students (id, age, department, firt_name, last_name) values (96, 29, 'Training', 'Emmye', 'Kinnard');
insert into students (id, age, department, firt_name, last_name) values (97, 50, 'Human Resources', 'Noreen', 'Anstiss');
insert into students (id, age, department, firt_name, last_name) values (98, 32, 'Human Resources', 'Mollee', 'Le Noire');
insert into students (id, age, department, firt_name, last_name) values (99, 43, 'Human Resources', 'Aleta', 'Frear');
insert into students (id, age, department, firt_name, last_name) values (100, 28, 'Engineering', 'Agneta', 'Belison');
insert into students (id, age, department, firt_name, last_name) values (101, 44, 'Accounting', 'Kaylee', 'Espinho');
insert into students (id, age, department, firt_name, last_name) values (102, 28, 'Human Resources', 'Wilie', 'Sedgemond');
insert into students (id, age, department, firt_name, last_name) values (103, 31, 'Product Management', 'Rena', 'Carnock');
insert into students (id, age, department, firt_name, last_name) values (104, 29, 'Business Development', 'Nissie', 'Headly');
insert into students (id, age, department, firt_name, last_name) values (105, 42, 'Engineering', 'Omero', 'Fowgies');
insert into students (id, age, department, firt_name, last_name) values (106, 30, 'Accounting', 'Bobbye', 'Ashton');
insert into students (id, age, department, firt_name, last_name) values (107, 32, 'Services', 'Reade', 'Jermey');
insert into students (id, age, department, firt_name, last_name) values (108, 34, 'Marketing', 'Clotilda', 'Biggs');
insert into students (id, age, department, firt_name, last_name) values (109, 30, 'Services', 'Kalli', 'Catcherside');
insert into students (id, age, department, firt_name, last_name) values (110, 37, 'Services', 'Dante', 'Macken');
insert into students (id, age, department, firt_name, last_name) values (111, 33, 'Business Development', 'Trevor', 'Chandler');
insert into students (id, age, department, firt_name, last_name) values (112, 35, 'Services', 'Harley', 'Bowshire');
insert into students (id, age, department, firt_name, last_name) values (113, 29, 'Product Management', 'Sargent', 'Ahmed');
insert into students (id, age, department, firt_name, last_name) values (114, 46, 'Training', 'Kathy', 'Gowthorpe');
insert into students (id, age, department, firt_name, last_name) values (115, 43, 'Business Development', 'Lynea', 'Dunk');
insert into students (id, age, department, firt_name, last_name) values (116, 39, 'Training', 'Fidole', 'Pottiphar');
insert into students (id, age, department, firt_name, last_name) values (117, 38, 'Human Resources', 'Norbert', 'Cheevers');
insert into students (id, age, department, firt_name, last_name) values (118, 36, 'Legal', 'Wilmette', 'ducarme');
insert into students (id, age, department, firt_name, last_name) values (119, 21, 'Training', 'Frank', 'Damper');
insert into students (id, age, department, firt_name, last_name) values (120, 23, 'Accounting', 'Dorothy', 'Tingey');
insert into students (id, age, department, firt_name, last_name) values (121, 40, 'Legal', 'Austin', 'Huffadine');
insert into students (id, age, department, firt_name, last_name) values (122, 37, 'Research and Development', 'Wye', 'Zorzutti');
insert into students (id, age, department, firt_name, last_name) values (123, 23, 'Product Management', 'Mathilda', 'Alexsandrev');
insert into students (id, age, department, firt_name, last_name) values (124, 34, 'Sales', 'Leonore', 'Stoyell');
insert into students (id, age, department, firt_name, last_name) values (125, 22, 'Sales', 'Clarice', 'Exton');
insert into students (id, age, department, firt_name, last_name) values (126, 37, 'Legal', 'Correy', 'Kimmince');
insert into students (id, age, department, firt_name, last_name) values (127, 36, 'Legal', 'Burt', 'Brea');
insert into students (id, age, department, firt_name, last_name) values (128, 39, 'Accounting', 'Herby', 'Meddick');
insert into students (id, age, department, firt_name, last_name) values (129, 37, 'Legal', 'Ferris', 'Maha');
insert into students (id, age, department, firt_name, last_name) values (130, 35, 'Research and Development', 'Jeannie', 'Brant');
insert into students (id, age, department, firt_name, last_name) values (131, 41, 'Legal', 'Leigh', 'Annear');
insert into students (id, age, department, firt_name, last_name) values (132, 34, 'Research and Development', 'Claiborn', 'Fishenden');
insert into students (id, age, department, firt_name, last_name) values (133, 41, 'Training', 'Konrad', 'Morena');
insert into students (id, age, department, firt_name, last_name) values (134, 34, 'Marketing', 'Roch', 'Bernardotte');
insert into students (id, age, department, firt_name, last_name) values (135, 37, 'Legal', 'Zenia', 'Sadlier');
insert into students (id, age, department, firt_name, last_name) values (136, 24, 'Training', 'Tiff', 'McCullogh');
insert into students (id, age, department, firt_name, last_name) values (137, 28, 'Sales', 'Carmella', 'Heinl');
insert into students (id, age, department, firt_name, last_name) values (138, 46, 'Marketing', 'Vince', 'Hugli');
insert into students (id, age, department, firt_name, last_name) values (139, 26, 'Accounting', 'Drusilla', 'Dugan');
insert into students (id, age, department, firt_name, last_name) values (140, 27, 'Accounting', 'Gregory', 'Madgin');
insert into students (id, age, department, firt_name, last_name) values (141, 50, 'Legal', 'Florie', 'Beumant');
insert into students (id, age, department, firt_name, last_name) values (142, 23, 'Support', 'Forrest', 'Southward');
insert into students (id, age, department, firt_name, last_name) values (143, 22, 'Legal', 'Kalila', 'Venturoli');
insert into students (id, age, department, firt_name, last_name) values (144, 45, 'Training', 'Valeda', 'Oneill');
insert into students (id, age, department, firt_name, last_name) values (145, 28, 'Support', 'Rudolf', 'Beckworth');
insert into students (id, age, department, firt_name, last_name) values (146, 42, 'Accounting', 'Anneliese', 'Merrisson');
insert into students (id, age, department, firt_name, last_name) values (147, 28, 'Services', 'Danika', 'Shoulders');
insert into students (id, age, department, firt_name, last_name) values (148, 30, 'Product Management', 'Rheta', 'Jancy');
insert into students (id, age, department, firt_name, last_name) values (149, 31, 'Marketing', 'Millie', 'Packham');
insert into students (id, age, department, firt_name, last_name) values (150, 50, 'Accounting', 'Hilary', 'Tattershall');
insert into students (id, age, department, firt_name, last_name) values (151, 48, 'Product Management', 'Stanislaus', 'Poate');
insert into students (id, age, department, firt_name, last_name) values (152, 32, 'Accounting', 'Isidor', 'Yakunikov');
insert into students (id, age, department, firt_name, last_name) values (153, 24, 'Product Management', 'Malanie', 'Sowley');
insert into students (id, age, department, firt_name, last_name) values (154, 48, 'Training', 'Antonetta', 'Leggs');
insert into students (id, age, department, firt_name, last_name) values (155, 28, 'Product Management', 'Forester', 'Hansbury');
insert into students (id, age, department, firt_name, last_name) values (156, 28, 'Sales', 'Wolfgang', 'Cooper');
insert into students (id, age, department, firt_name, last_name) values (157, 29, 'Business Development', 'Sunny', 'Bredgeland');
insert into students (id, age, department, firt_name, last_name) values (158, 20, 'Legal', 'Gilly', 'Tumility');
insert into students (id, age, department, firt_name, last_name) values (159, 24, 'Marketing', 'Kenon', 'Lanston');
insert into students (id, age, department, firt_name, last_name) values (160, 33, 'Research and Development', 'Dusty', 'Yong');
insert into students (id, age, department, firt_name, last_name) values (161, 50, 'Engineering', 'Bea', 'Flippen');
insert into students (id, age, department, firt_name, last_name) values (162, 30, 'Business Development', 'Maddi', 'Awdry');
insert into students (id, age, department, firt_name, last_name) values (163, 30, 'Accounting', 'Munroe', 'Grummitt');
insert into students (id, age, department, firt_name, last_name) values (164, 34, 'Research and Development', 'Sula', 'Fassmann');
insert into students (id, age, department, firt_name, last_name) values (165, 31, 'Training', 'Doe', 'Van der Hoeven');
insert into students (id, age, department, firt_name, last_name) values (166, 33, 'Support', 'Raphaela', 'Upshall');
insert into students (id, age, department, firt_name, last_name) values (167, 19, 'Engineering', 'Shoshana', 'Bootes');
insert into students (id, age, department, firt_name, last_name) values (168, 31, 'Business Development', 'Brande', 'Ramme');
insert into students (id, age, department, firt_name, last_name) values (169, 25, 'Sales', 'Robenia', 'Aubery');
insert into students (id, age, department, firt_name, last_name) values (170, 30, 'Sales', 'Durant', 'Finn');
insert into students (id, age, department, firt_name, last_name) values (171, 48, 'Legal', 'Cherri', 'Densham');
insert into students (id, age, department, firt_name, last_name) values (172, 25, 'Engineering', 'Mirna', 'Tubby');
insert into students (id, age, department, firt_name, last_name) values (173, 38, 'Research and Development', 'Ermina', 'Wivell');
insert into students (id, age, department, firt_name, last_name) values (174, 34, 'Research and Development', 'Jens', 'Planke');
insert into students (id, age, department, firt_name, last_name) values (175, 50, 'Product Management', 'Beaufort', 'Paget');
insert into students (id, age, department, firt_name, last_name) values (176, 39, 'Accounting', 'Angelique', 'Luckin');
insert into students (id, age, department, firt_name, last_name) values (177, 35, 'Human Resources', 'Darrick', 'Magog');
insert into students (id, age, department, firt_name, last_name) values (178, 23, 'Research and Development', 'Zacherie', 'Brisco');
insert into students (id, age, department, firt_name, last_name) values (179, 26, 'Research and Development', 'Tadd', 'Denacamp');
insert into students (id, age, department, firt_name, last_name) values (180, 47, 'Engineering', 'Lilla', 'Lude');
insert into students (id, age, department, firt_name, last_name) values (181, 37, 'Legal', 'Nicholas', 'Riordan');
insert into students (id, age, department, firt_name, last_name) values (182, 45, 'Legal', 'Jamesy', 'Davidowich');
insert into students (id, age, department, firt_name, last_name) values (183, 46, 'Sales', 'Bard', 'Trulock');
insert into students (id, age, department, firt_name, last_name) values (184, 37, 'Sales', 'Wayne', 'Sturley');
insert into students (id, age, department, firt_name, last_name) values (185, 45, 'Engineering', 'Randal', 'Priestley');
insert into students (id, age, department, firt_name, last_name) values (186, 47, 'Training', 'Catherine', 'Bentham');
insert into students (id, age, department, firt_name, last_name) values (187, 22, 'Human Resources', 'Constantino', 'Feaviour');
insert into students (id, age, department, firt_name, last_name) values (188, 34, 'Sales', 'Sumner', 'Neem');
insert into students (id, age, department, firt_name, last_name) values (189, 29, 'Legal', 'Wynn', 'Rainton');
insert into students (id, age, department, firt_name, last_name) values (190, 20, 'Engineering', 'Rafi', 'Thursby');
insert into students (id, age, department, firt_name, last_name) values (191, 25, 'Engineering', 'Shayla', 'Dorsett');
insert into students (id, age, department, firt_name, last_name) values (192, 37, 'Marketing', 'Doreen', 'Newberry');
insert into students (id, age, department, firt_name, last_name) values (193, 44, 'Accounting', 'Lindie', 'Reast');
insert into students (id, age, department, firt_name, last_name) values (194, 37, 'Training', 'Lydon', 'Capon');
insert into students (id, age, department, firt_name, last_name) values (195, 47, 'Product Management', 'Georgy', 'Cunio');
insert into students (id, age, department, firt_name, last_name) values (196, 37, 'Training', 'Edi', 'MacFadzean');
insert into students (id, age, department, firt_name, last_name) values (197, 28, 'Product Management', 'Dael', 'De Antoni');
insert into students (id, age, department, firt_name, last_name) values (198, 43, 'Marketing', 'Meridel', 'Langford');
insert into students (id, age, department, firt_name, last_name) values (199, 37, 'Services', 'Maurie', 'Bloxham');
insert into students (id, age, department, firt_name, last_name) values (200, 37, 'Business Development', 'Desirae', 'Lentsch');
